# This workflow will do a clean install of node dependencies and build the source code of Liquid Prep App and backend service for node version 14.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Liquid Prep CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_web_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./liquid-prep-app
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Rename sample config file
      run: |
        cd src
        mv config-sample.json config.json
        ls -l config.json
        cd ../
    - name: Install node dependencies and build the project
      run: |
        npm install
        npm run build --prod
  build_backend_service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install Node dependencies for common folder
      run: |
        cd common
        npm install
        cd ../
    - name: Install Node dependencies for cloud functions and build
      run: |
        cd liquid-prep-cf
        npm install
        npm run build
        npm run bundle